---
title: "ACE results, new"
author: "Monica Thieu"
date: "August 12, 2016"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(knitr)
library(ggplot2)
library(tidyr)
library(plyr)
library(dplyr)
library(lazyeval)
library(outliers)
library(gtools)


source("../R/brt_append.R") # loading in helper functions
source("../R/clean_grade_gender.R")
source("../R/get_outlier_subs.R")
# note to self: now I am extremely concerned about multiple comparisons... I'll do an FDR using n = n_modules * n_varspermodule at some point?
# note: supports flexibility in grade labels, but please beware of over-interpreting gradewise differences when N by grade is low
```

```{r defining printing args READ ME}
# Please set each of these to TRUE or FALSE depending on whether you would like info on the module printed to the summary document.
BRT_PRINT = T
BOX_PRINT = T
FLANK_PRINT = T
SAAT_PRINT = T
SPAN_PRINT = T
BSPAN_PRINT = F
STROOP_PRINT = T
SWITCH_PRINT = T
TNT_PRINT = T
FILTER_PRINT = F

# Please set these to TRUE or FALSE depending on whether you would like outlier checking info or quality control histograms printed for ALL modules or not. Even if these are set to TRUE, they will not print for modules which have been turned off (set as FALSE) in the above block.
OUTLIER_PRINT = TRUE
QC_HIST_PRINT = TRUE

# Please set this to TRUE or FALSE depending on whether you would like ALL continuous x-regressors z-scored. They will always be mean-centered; this just z-scores them by further dividing them by std dev.
Z_SCORE_XREGS = FALSE
```


```{r loading cached -by hand- data}
# load(file = "~/Dropbox/aceR/seacrest_data/clean_data.RData")
load(file = "~/Documents/ace_large_data/almost_all_preproc_122816.RData") # var named proc_demo
proc_pre = proc_demo
load(file = "~/Documents/ace_large_data/s17_preproc_071717.RData") # var named proc_s17_all
proc_post = proc_s17_all
```

```{r read_chunking, cache=FALSE}
read_chunk("../markdowns/single_module_prepost_md.R")
```

```{r school prefixes}
prefixes = c("br", "pe", "la", "se", "ca", "bo", "mh", "mk")
schools = c("Bracher", "Peterson", "Laurelwood", "Seacrest", "Cabrillo", "Bowers", "Most Holy Trinity", "Millikin")
```


```{r setting vars for BRT READ ME}
this_task = "BRT"
this_task_long = "BRT"
vars_of_interest = c("rt_mean.right", "rt_mean.left")
vars_of_interest_long = c("Mean RT--right hand", "Mean RT--left hand") # nice version for printing in graphs
score_vars = c("rt_mean.overall")
score_formula = NA
```

```{r brt load}
if(this_task == "BRT" & !BRT_PRINT) {} else { # edge case where BRT needs to be evaluated even if no print (and thus header turned off)
  paste0("#", this_task_long) %>%
    asis_output()}
cat("\n") %>% asis_output() # need this for line breaking

d_pre_raw <- proc_pre[[this_task]]
d_post_raw <- proc_post[[this_task]]
```

```{r brt pre outliers}
remove_outlier_subs <- function(d_raw, vars_of_interest) {
  bad_subs = vector("list", length(unique(d_raw$grade)))
  for (i in 1:length(vars_of_interest)) {# for each grade, concatenates outliers ACROSS metrics of interest
    for (j in 1:length(unique(d_raw$grade))) {
      # need this to verify that there are >2 valid data pts in this grade level to do the outlier test
      these_vals_temp = with(d_raw, get(vars_of_interest[i])[grade == unique(grade)[j] & !is.na(get(vars_of_interest[i]))])
      if(length(these_vals_temp) > 2) {
        these_bad_subs = d_raw %>%
          filter(grade == unique(grade)[j]) %>%
          with(
            get_outlier_subs(get(vars_of_interest[i]), pid))
      } else {these_bad_subs = NULL}
      if(!is.null(these_bad_subs)) {bad_subs[[j]] <- c(bad_subs[[j]], these_bad_subs)}
    }
  }
  
  return(d_raw %>% filter(!(pid %in% unlist(bad_subs))))
}

d_pre = remove_outlier_subs(d_pre_raw, vars_of_interest) %>%
  clean_grade_gender()
```

```{r caching brt pre for appending to subsequent modules}
brt_pre <- d_pre
```

```{r score feedback brt pre, eval=BRT_PRINT}
asis_output("##Pre\n")
asis_output("###mean scores for giving feedback in task\n")

calc_scores <- function(d, score_vars, score_formula) {
  if(is.na(score_formula)) {
    d_score = d %>%
      group_by(grade) %>%
      select(one_of(score_vars))
    
    if(length(score_vars) == 1) {
      d_score = d_score %>%
        summarize_(var1_mean = interp(~mean(a, na.rm=T), a = as.name(score_vars[1])),
                   var1_sd = interp(~sd(a, na.rm=T), a = as.name(score_vars[1])))
      cat("var1: ", score_vars) 
    } else if(length(score_vars) == 2) {
      d_score = d_score %>%
        summarize_(var1_mean = interp(~mean(a, na.rm=T), a = as.name(score_vars[1])),
                   var1_sd = interp(~sd(a, na.rm=T), a = as.name(score_vars[1])),
                   var2_mean = interp(~mean(a, na.rm=T), a = as.name(score_vars[2])),
                   var2_sd = interp(~sd(a, na.rm=T), a = as.name(score_vars[2])))
      cat("var1:", score_vars[1], "\nvar2:", score_vars[2])
    }
  } else if(score_formula == "fraction") {
    cat("score formula: ((((b-a)/a) * 100) + 100) \na:", score_vars[1], "\nb:", score_vars[2])
    d_score = d %>%
      mutate_(score = interp(~((((b-a)/a)*100)+100), a = as.name(score_vars[1]), b = as.name(score_vars[2]))) %>%
      group_by(grade) %>%
      select(score) %>%
      summarize(score_mean = mean(score),
                score_sd = sd(score))
  }
  return(d_score)
}

d_score = calc_scores(d_pre, score_vars, NA)
print(d_score)
```

```{r qc graphs brt pre, eval=(BRT_PRINT & QC_HIST_PRINT)}
asis_output("###quality control histograms\n")
paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()
d_pre %>%
  ggplot(aes(x = get(vars_of_interest[1]), fill = factor(grade_label))) +
  geom_histogram(bins=20, position="dodge") +
  labs(x = vars_of_interest_long[1]) +
  guides(fill = guide_legend(title = "Grade"))

cat("\n") %>% asis_output()
if(!invalid(vars_of_interest[2])) {
  paste("####", vars_of_interest_long[2], sep = "") %>%
    asis_output()}
if(!invalid(vars_of_interest[2])) {
  d_pre %>%
    ggplot(aes(x = get(vars_of_interest[2]), fill = factor(grade_label))) +
    geom_histogram(bins=20, position="dodge") +
    labs(x = vars_of_interest_long[2]) +
    guides(fill = guide_legend(title = "Grade"))}
```

```{r lms brt only pre, eval=BRT_PRINT}
asis_output("###regressions\n")
paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()
d_pre %>%
  with(summary(lm(get(vars_of_interest[1]) ~ grade * gender)))

cat("\n") %>% asis_output()
if(!invalid(vars_of_interest[2])) {
  paste("####", vars_of_interest_long[2], sep = "") %>%
    asis_output()} # dumb: they have to be in two separate if statements to get the heading to render
if(!invalid(vars_of_interest[2])) {
  d_pre %>%
    with(summary(lm(get(vars_of_interest[2]) ~ grade * gender)))}
```

```{r brt post outliers n preproc}
d_post <- remove_outlier_subs(d_post_raw, vars_of_interest) %>%
  clean_grade_gender()
```

```{r caching brt post for appending to subsequent modules}
brt_post <- d_post
```

```{r score feedback brt post, eval=BRT_PRINT}
asis_output("##Post\n")
asis_output("###mean scores for giving feedback in task\n")

d_score = calc_scores(d_post, score_vars, score_formula = NA)
print(d_score)
```

```{r qc graphs brt post, eval=(BRT_PRINT & QC_HIST_PRINT)}
asis_output("###quality control histograms\n")
paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()
d_post %>%
  ggplot(aes(x = get(vars_of_interest[1]), fill = factor(grade_label))) +
  geom_histogram(bins=20, position="dodge") +
  labs(x = vars_of_interest_long[1]) +
  guides(fill = guide_legend(title = "Grade"))

cat("\n") %>% asis_output()
if(!invalid(vars_of_interest[2])) {
  paste("####", vars_of_interest_long[2], sep = "") %>%
    asis_output()}
if(!invalid(vars_of_interest[2])) {
  d_post %>%
    ggplot(aes(x = get(vars_of_interest[2]), fill = factor(grade_label))) +
    geom_histogram(bins=20, position="dodge") +
    labs(x = vars_of_interest_long[2]) +
    guides(fill = guide_legend(title = "Grade"))}
```

```{r lms brt only post, eval=BRT_PRINT}
asis_output("###regressions\n")
paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()
d_post %>%
  with(summary(lm(get(vars_of_interest[1]) ~ grade * gender)))

cat("\n") %>% asis_output()
if(!invalid(vars_of_interest[2])) {
  paste("####", vars_of_interest_long[2], sep = "") %>%
    asis_output()} # dumb: they have to be in two separate if statements to get the heading to render
if(!invalid(vars_of_interest[2])) {
  d_post %>%
    with(summary(lm(get(vars_of_interest[2]) ~ grade * gender)))}
```

```{r brt preproc pre vs post, eval=BRT_PRINT}
preproc_pre_v_post <- function(d_pre, d_post, vars_of_interest) {
  d_pre <- d_pre %>%
    select(pid, grade:gender, grade_label, one_of(vars_of_interest)) %>%
    group_by(pid, grade, gender, grade_label) %>% summarize_at(one_of(vars_of_interest), mean, na.rm = T) %>%
    ungroup()
  d_post <- d_post %>%
    select(pid, grade:gender, grade_label, one_of(vars_of_interest)) %>%
    group_by(pid, grade, gender, grade_label) %>% summarize_at(one_of(vars_of_interest), mean, na.rm = T) %>%
    ungroup()
  d_all <- d_pre %>%
    inner_join(d_post, by = c("pid", "grade", "grade_label", "gender"), suffix = c("-pre", "-post"))
  d_all <- mutate_(d_all,
                   var1_diff = interp(~(b - a), a = as.name(paste0(vars_of_interest[1], "-post")), b = as.name(paste0(vars_of_interest[1], "-pre"))))
  if(!invalid(vars_of_interest[2])) {
    d_all <- mutate_(d_all,
                     var2_diff = interp(~(b - a), a = as.name(paste0(vars_of_interest[2], "-post")), b = as.name(paste0(vars_of_interest[2], "-pre"))))
  }
  if(!invalid(vars_of_interest[3])) {
    d_all <- mutate_(d_all,
                     var3_diff = interp(~(b - a), a = as.name(paste0(vars_of_interest[3], "-post")), b = as.name(paste0(vars_of_interest[3], "-pre"))))
  }
  return(d_all)
}
d_all = preproc_pre_v_post(brt_pre, brt_post, vars_of_interest)
```

```{r brt lms pre vs post, eval=BRT_PRINT}
asis_output("##Pre vs. post\n")
asis_output("###regressions\n")
paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()
d_all %>%
  with(summary(lm(var1_diff ~ grade * gender)))

cat("\n") %>% asis_output()
if(!invalid(vars_of_interest[2])) {
  paste("####", vars_of_interest_long[2], sep = "") %>%
    asis_output()} # dumb: they have to be in two separate if statements to get the heading to render
if(!invalid(vars_of_interest[2])) {
  d_all %>%
    with(summary(lm(var2_diff ~ grade * gender)))}
```

```{r brt graphs pre vs post, eval=BRT_PRINT}
asis_output("###graphs\n")
paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()

make_long_pvp <- function(d_all) {
  d_long <- d_all %>%
    select(-starts_with("var")) %>%
    gather(pre_or_post, value, -c(pid:grade_label)) %>%
    extract(pre_or_post, c("var_name", "pre_or_post"), "([[:alnum:]]+_[[:alnum:]]+.[[:alnum:]]+)-([[:alnum:]]+)") %>%
    spread(var_name, value) %>%
    mutate(pre_or_post = factor(pre_or_post, levels = c("pre", "post")))
  return(d_long)
}

d_long = make_long_pvp(d_all)

d_long %>%
  ggplot(aes(x = grade_label, y = rt_mean.right, fill = factor(gender))) +
  geom_boxplot() +
  facet_grid(~ pre_or_post) +
  labs(y = vars_of_interest_long[1]) +
  guides(fill = guide_legend(title = "Gender"))

cat("\n") %>% asis_output()
paste("####", vars_of_interest_long[2], sep = "") %>%
  asis_output()
d_long %>%
  ggplot(aes(x = grade_label, y = rt_mean.left, fill = factor(gender))) +
  geom_boxplot() +
  facet_grid(~ pre_or_post) +
  labs(y = vars_of_interest_long[2]) +
  guides(fill = guide_legend(title = "Gender"))
```

```{r setting vars for boxed READ ME}
this_task = "BOXED"
this_task_long = "Boxed"
vars_of_interest = "rt_mean.overall"
vars_of_interest_long = "Mean overall RT" # nice version for printing in graphs
score_vars = c("rt_mean.conjunction_4", "rt_mean.conjunction_12")
score_formula = "fraction"
```

```{r boxed load, eval = BOX_PRINT}
paste0("#", this_task_long) %>% asis_output()
cat("\n") %>% asis_output() # need this for line breaking

d_pre_raw <- proc_pre[[this_task]]
d_post_raw <- proc_post[[this_task]]

d_pre = remove_outlier_subs(d_pre_raw, vars_of_interest) %>%
  brt_append(brt_pre) %>%
  clean_grade_gender()
```

```{r score feedback boxed pre, eval=BOX_PRINT}
asis_output("##Pre\n")
asis_output("###mean scores for giving feedback in task\n")

d_score = calc_scores(d_pre, score_vars, score_formula)
print(d_score)
```

```{r qc graphs boxed pre, eval=(BOX_PRINT & QC_HIST_PRINT)}
asis_output("###quality control histograms\n")
paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()
d_pre %>%
  ggplot(aes(x = get(vars_of_interest[1]), fill = factor(grade_label))) +
  geom_histogram(bins=20, position="dodge") +
  labs(x = vars_of_interest_long[1]) +
  guides(fill = guide_legend(title = "Grade"))
```

```{r lms boxed pre, eval=BOX_PRINT}
asis_output("###regressions\n")
paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()
d_pre %>%
  with(summary(lm(get(vars_of_interest[1]) ~ grade * gender + scale(brt_rt_mean.overall, scale = Z_SCORE_XREGS))))
```

```{r boxed post outliers, eval = BOX_PRINT}
d_post <- remove_outlier_subs(d_post_raw, vars_of_interest) %>%
  brt_append(brt_post) %>%
  clean_grade_gender()
```

```{r score feedback boxed post, eval=BOX_PRINT}
asis_output("##Post\n")
asis_output("###mean scores for giving feedback in task\n")

d_score = calc_scores(d_post, score_vars, score_formula = NA)
print(d_score)
```

```{r qc graphs boxed post, eval=(BOX_PRINT & QC_HIST_PRINT)}
asis_output("###quality control histograms\n")
paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()
d_post %>%
  ggplot(aes(x = get(vars_of_interest[1]), fill = factor(grade_label))) +
  geom_histogram(bins=20, position="dodge") +
  labs(x = vars_of_interest_long[1]) +
  guides(fill = guide_legend(title = "Grade"))
```

```{r lms boxed post, eval=BOX_PRINT}
asis_output("###regressions\n")
paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()
d_post %>%
  with(summary(lm(get(vars_of_interest[1]) ~ grade * gender + scale(brt_rt_mean.overall, scale = Z_SCORE_XREGS))))
```

```{r boxed preproc pre vs post, eval=BOX_PRINT}
d_all = preproc_pre_v_post(d_pre, d_post, vars_of_interest)
```

```{r boxed lms pre vs post, eval=BOX_PRINT}
asis_output("##Pre vs. post\n")
asis_output("###regressions\n")
paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()
d_all %>%
  with(summary(lm(var1_diff ~ grade * gender)))
```

```{r boxed graphs pre vs post, eval=BOX_PRINT}
asis_output("###graphs\n")
paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()

d_long = make_long_pvp(d_all)

d_long %>%
  ggplot(aes(x = grade_label, y = get(vars_of_interest[1]), fill = factor(gender))) +
  geom_boxplot() +
  facet_grid(~ pre_or_post) +
  labs(y = vars_of_interest_long[1]) +
  guides(fill = guide_legend(title = "Gender"))
```

```{r setting vars for flanker READ ME}
this_task = "FLANKER"
this_task_long = "Flanker"
vars_of_interest = c("rt_mean.congruent","rt_mean.incongruent","rt_mean.cost")
vars_of_interest_long = c("Mean RT--congruent trials", "Mean RT--incongruent trials", "Mean cost of incongruence on RT") # nice version for printing in graphs
score_vars = c("rt_mean.congruent", "rt_mean.incongruent")
score_formula = "fraction"
```

```{r flanker load, eval = FLANK_PRINT}
paste0("#", this_task_long) %>% asis_output()
cat("\n") %>% asis_output() # need this for line breaking

d_pre_raw <- proc_pre[[this_task]]
d_post_raw <- proc_post[[this_task]]

d_pre = remove_outlier_subs(d_pre_raw, vars_of_interest) %>%
  brt_append(brt_pre) %>%
  clean_grade_gender()
```

```{r score feedback flanker pre, eval=FLANK_PRINT}
asis_output("##Pre\n")
asis_output("###mean scores for giving feedback in task\n")

d_score = calc_scores(d_pre, score_vars, score_formula)
print(d_score)
```

```{r qc graphs flanker pre, eval=(FLANK_PRINT & QC_HIST_PRINT)}
asis_output("###quality control histograms\n")
paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()

d_pre %>%
  ggplot(aes(x = get(vars_of_interest[1]), fill = factor(grade_label))) +
  geom_histogram(bins=20, position="dodge") +
  labs(x = vars_of_interest_long[1]) +
  guides(fill = guide_legend(title = "Grade"))

asis_output(cat("####", vars_of_interest_long[2], "\n"))
d_pre %>%
  ggplot(aes(x = get(vars_of_interest[2]), fill = factor(grade_label))) +
  geom_histogram(bins=20, position="dodge") +
  labs(x = vars_of_interest_long[2]) +
  guides(fill = guide_legend(title = "Grade"))

asis_output(cat("####", vars_of_interest_long[3], "\n"))
d_pre %>%
  ggplot(aes(x = get(vars_of_interest[3]), fill = factor(grade_label))) +
  geom_histogram(bins=20, position="dodge") +
  labs(x = vars_of_interest_long[3]) +
  guides(fill = guide_legend(title = "Grade"))
```

```{r lms flanker pre, eval=FLANK_PRINT}
asis_output("###regressions\n")
paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()
d_pre %>%
  with(summary(lm(get(vars_of_interest[1]) ~ grade * gender + scale(brt_rt_mean.overall, scale = Z_SCORE_XREGS))))

paste("####", vars_of_interest_long[2], sep = "") %>%
  asis_output()
d_pre %>%
  with(summary(lm(get(vars_of_interest[2]) ~ grade * gender + scale(brt_rt_mean.overall, scale = Z_SCORE_XREGS))))

paste("####", vars_of_interest_long[3], sep = "") %>%
  asis_output()
d_pre %>%
  with(summary(lm(get(vars_of_interest[3]) ~ grade * gender + scale(brt_rt_mean.overall, scale = Z_SCORE_XREGS))))
```

```{r flanker post outliers, eval = FLANK_PRINT}
d_post <- remove_outlier_subs(d_post_raw, vars_of_interest) %>%
  brt_append(brt_post) %>%
  clean_grade_gender()
```

```{r score feedback flanker post, eval=FLANK_PRINT}
asis_output("##Post\n")
asis_output("###mean scores for giving feedback in task\n")

d_score = calc_scores(d_post, score_vars, score_formula)
print(d_score)
```

```{r qc graphs flanker post, eval=(FLANK_PRINT & QC_HIST_PRINT)}
asis_output("###quality control histograms\n")
paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()
d_post %>%
  ggplot(aes(x = get(vars_of_interest[1]), fill = factor(grade_label))) +
  geom_histogram(bins=20, position="dodge") +
  labs(x = vars_of_interest_long[1]) +
  guides(fill = guide_legend(title = "Grade"))

paste("####", vars_of_interest_long[2], sep = "") %>%
  asis_output()
d_post %>%
  ggplot(aes(x = get(vars_of_interest[2]), fill = factor(grade_label))) +
  geom_histogram(bins=20, position="dodge") +
  labs(x = vars_of_interest_long[2]) +
  guides(fill = guide_legend(title = "Grade"))

paste("####", vars_of_interest_long[3], sep = "") %>%
  asis_output()
d_post %>%
  ggplot(aes(x = get(vars_of_interest[3]), fill = factor(grade_label))) +
  geom_histogram(bins=20, position="dodge") +
  labs(x = vars_of_interest_long[3]) +
  guides(fill = guide_legend(title = "Grade"))
```

```{r lms flanker post, eval=FLANK_PRINT}
asis_output("###regressions\n")
paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()
d_post %>%
  with(summary(lm(get(vars_of_interest[1]) ~ grade * gender + scale(brt_rt_mean.overall, scale = Z_SCORE_XREGS))))

paste("####", vars_of_interest_long[2], sep = "") %>%
  asis_output()
d_post %>%
  with(summary(lm(get(vars_of_interest[2]) ~ grade * gender + scale(brt_rt_mean.overall, scale = Z_SCORE_XREGS))))

paste("####", vars_of_interest_long[3], sep = "") %>%
  asis_output()
d_post %>%
  with(summary(lm(get(vars_of_interest[3]) ~ grade * gender + scale(brt_rt_mean.overall, scale = Z_SCORE_XREGS))))
```

```{r flanker preproc pre vs post, eval=FLANK_PRINT}
d_all = preproc_pre_v_post(d_pre, d_post, vars_of_interest)
```

```{r flanker lms pre vs post, eval=FLANK_PRINT}
asis_output("##Pre vs. post\n")
asis_output("###regressions\n")
asis_output(cat("####", vars_of_interest_long[1], "\n"))
d_all %>%
  with(summary(lm(var1_diff ~ grade * gender)))

asis_output(cat("####", vars_of_interest_long[2], "\n"))
d_all %>%
  with(summary(lm(var2_diff ~ grade * gender)))

asis_output(cat("####", vars_of_interest_long[3], "\n"))
d_all %>%
  with(summary(lm(var3_diff ~ grade * gender)))
```

```{r flanker graphs pre vs post, eval=FLANK_PRINT}
asis_output("###graphs\n")

d_long = make_long_pvp(d_all)

paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()

d_long %>%
  ggplot(aes(x = grade_label, y = get(vars_of_interest[1]), fill = factor(gender))) +
  geom_boxplot() +
  facet_grid(~ pre_or_post) +
  labs(y = vars_of_interest_long[1]) +
  guides(fill = guide_legend(title = "Gender"))

paste("####", vars_of_interest_long[2], sep = "") %>%
  asis_output()

d_long %>%
  ggplot(aes(x = grade_label, y = get(vars_of_interest[2]), fill = factor(gender))) +
  geom_boxplot() +
  facet_grid(~ pre_or_post) +
  labs(y = vars_of_interest_long[2]) +
  guides(fill = guide_legend(title = "Gender"))

paste("####", vars_of_interest_long[3], sep = "") %>%
  asis_output()

d_long %>%
  ggplot(aes(x = grade_label, y = get(vars_of_interest[3]), fill = factor(gender))) +
  geom_boxplot() +
  facet_grid(~ pre_or_post) +
  labs(y = vars_of_interest_long[3]) +
  guides(fill = guide_legend(title = "Gender"))
```

```{r setting vars for saat READ ME}
this_task = "SAAT"
this_task_long = "SAAT"
vars_of_interest = c("rt_mean.sustained","rt_mean.impulsive")
vars_of_interest_long = c("Mean RT--sustained trials", "Mean RT--impulsive trials") # nice version for printing in graphs
score_vars = vars_of_interest
score_formula = NA
```

```{r saat load, eval = SAAT_PRINT}
paste0("#", this_task_long) %>% asis_output()
cat("\n") %>% asis_output() # need this for line breaking

d_pre_raw <- proc_pre[[this_task]]
d_post_raw <- proc_post[[this_task]]

d_pre = remove_outlier_subs(d_pre_raw, vars_of_interest) %>%
  brt_append(brt_pre) %>%
  clean_grade_gender()
```

```{r score feedback saat pre, eval=SAAT_PRINT}
asis_output("##Pre\n")
asis_output("###mean scores for giving feedback in task\n")

d_score = calc_scores(d_pre, score_vars, score_formula)
print(d_score)
```

```{r qc graphs saat pre, eval=(SAAT_PRINT & QC_HIST_PRINT)}
asis_output("###quality control histograms\n")
paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()

d_pre %>%
  ggplot(aes(x = get(vars_of_interest[1]), fill = factor(grade_label))) +
  geom_histogram(bins=20, position="dodge") +
  labs(x = vars_of_interest_long[1]) +
  guides(fill = guide_legend(title = "Grade"))

asis_output(cat("####", vars_of_interest_long[2], "\n"))
d_pre %>%
  ggplot(aes(x = get(vars_of_interest[2]), fill = factor(grade_label))) +
  geom_histogram(bins=20, position="dodge") +
  labs(x = vars_of_interest_long[2]) +
  guides(fill = guide_legend(title = "Grade"))
```

```{r lms saat pre, eval=SAAT_PRINT}
asis_output("###regressions\n")
paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()
d_pre %>%
  with(summary(lm(get(vars_of_interest[1]) ~ grade * gender + scale(brt_rt_mean.overall, scale = Z_SCORE_XREGS))))

paste("####", vars_of_interest_long[2], sep = "") %>%
  asis_output()
d_pre %>%
  with(summary(lm(get(vars_of_interest[2]) ~ grade * gender + scale(brt_rt_mean.overall, scale = Z_SCORE_XREGS))))
```

```{r saat post outliers, eval = SAAT_PRINT}
d_post <- remove_outlier_subs(d_post_raw, vars_of_interest) %>%
  brt_append(brt_post) %>%
  clean_grade_gender()
```

```{r score feedback saat post, eval=SAAT_PRINT}
asis_output("##Post\n")
asis_output("###mean scores for giving feedback in task\n")

d_score = calc_scores(d_post, score_vars, score_formula)
print(d_score)
```

```{r qc graphs saat post, eval=(SAAT_PRINT & QC_HIST_PRINT)}
asis_output("###quality control histograms\n")
paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()
d_post %>%
  ggplot(aes(x = get(vars_of_interest[1]), fill = factor(grade_label))) +
  geom_histogram(bins=20, position="dodge") +
  labs(x = vars_of_interest_long[1]) +
  guides(fill = guide_legend(title = "Grade"))

paste("####", vars_of_interest_long[2], sep = "") %>%
  asis_output()
d_post %>%
  ggplot(aes(x = get(vars_of_interest[2]), fill = factor(grade_label))) +
  geom_histogram(bins=20, position="dodge") +
  labs(x = vars_of_interest_long[2]) +
  guides(fill = guide_legend(title = "Grade"))
```

```{r lms saat post, eval=SAAT_PRINT}
asis_output("###regressions\n")
paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()
d_post %>%
  with(summary(lm(get(vars_of_interest[1]) ~ grade * gender + scale(brt_rt_mean.overall, scale = Z_SCORE_XREGS))))

paste("####", vars_of_interest_long[2], sep = "") %>%
  asis_output()
d_post %>%
  with(summary(lm(get(vars_of_interest[2]) ~ grade * gender + scale(brt_rt_mean.overall, scale = Z_SCORE_XREGS))))
```

```{r saat preproc pre vs post, eval=SAAT_PRINT}
d_all = preproc_pre_v_post(d_pre, d_post, vars_of_interest)
```

```{r saat lms pre vs post, eval=SAAT_PRINT}
asis_output("##Pre vs. post\n")
asis_output("###regressions\n")
asis_output(cat("####", vars_of_interest_long[1], "\n"))
d_all %>%
  with(summary(lm(var1_diff ~ grade * gender)))

asis_output(cat("####", vars_of_interest_long[2], "\n"))
d_all %>%
  with(summary(lm(var2_diff ~ grade * gender)))
```

```{r saat graphs pre vs post, eval=SAAT_PRINT}
asis_output("###graphs\n")

d_long = make_long_pvp(d_all)

paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()

d_long %>%
  ggplot(aes(x = grade_label, y = get(vars_of_interest[1]), fill = factor(gender))) +
  geom_boxplot() +
  facet_grid(~ pre_or_post) +
  labs(y = vars_of_interest_long[1]) +
  guides(fill = guide_legend(title = "Gender"))

paste("####", vars_of_interest_long[2], sep = "") %>%
  asis_output()

d_long %>%
  ggplot(aes(x = grade_label, y = get(vars_of_interest[2]), fill = factor(gender))) +
  geom_boxplot() +
  facet_grid(~ pre_or_post) +
  labs(y = vars_of_interest_long[2]) +
  guides(fill = guide_legend(title = "Gender"))
```

```{r setting vars for span READ ME}
this_task = "SPATIALSPAN"
this_task_long = "Spatial span"
vars_of_interest = "object_count_span.overall"
vars_of_interest_long = "Overall span (obj count)" # nice version for printing in graphs
# NOT running the outlier check on the object span metric... I think I broke grubbs.test
score_vars = vars_of_interest
score_formula = NA
```


```{r spatial span load, eval = SPAN_PRINT}
paste0("#", this_task_long) %>% asis_output()
cat("\n") %>% asis_output() # need this for line breaking

d_pre_raw <- proc_pre[[this_task]]
d_post_raw <- proc_post[[this_task]]

d_pre = brt_append(d_pre_raw, brt_pre, ext_demo_data = F) %>%
  clean_grade_gender()
```

```{r score feedback spatial span pre, eval=SPAN_PRINT}
asis_output("##Pre\n")
asis_output("###mean scores for giving feedback in task\n")

d_score = calc_scores(d_pre, score_vars, score_formula)
print(d_score)
```

```{r qc graphs spatial span pre, eval=(SPAN_PRINT & QC_HIST_PRINT)}
asis_output("###quality control histograms\n")
paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()
d_pre %>%
  ggplot(aes(x = get(vars_of_interest[1]), fill = factor(grade_label))) +
  geom_histogram(bins=20, position="dodge") +
  labs(x = vars_of_interest_long[1]) +
  guides(fill = guide_legend(title = "Grade"))
```

```{r lms spatial span pre, eval=SPAN_PRINT}
asis_output("###regressions\n")
paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()
d_pre %>%
  with(summary(lm(get(vars_of_interest[1]) ~ grade * gender + scale(brt_rt_mean.overall, scale = Z_SCORE_XREGS))))
```

```{r spatial span post outliers, eval = SPAN_PRINT}
d_post <- d_post_raw %>%
  brt_append(brt_post) %>%
  clean_grade_gender()
```

```{r score feedback spatial span post, eval=SPAN_PRINT}
asis_output("##Post\n")
asis_output("###mean scores for giving feedback in task\n")

d_score = calc_scores(d_post, score_vars, score_formula = NA)
print(d_score)
```

```{r qc graphs spatial span post, eval=(SPAN_PRINT & QC_HIST_PRINT)}
asis_output("###quality control histograms\n")
paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()
d_post %>%
  ggplot(aes(x = get(vars_of_interest[1]), fill = factor(grade_label))) +
  geom_histogram(bins=20, position="dodge") +
  labs(x = vars_of_interest_long[1]) +
  guides(fill = guide_legend(title = "Grade"))
```

```{r lms spatial span post, eval=SPAN_PRINT}
asis_output("###regressions\n")
paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()
d_post %>%
  with(summary(lm(get(vars_of_interest[1]) ~ grade * gender + scale(brt_rt_mean.overall, scale = Z_SCORE_XREGS))))
```

```{r spatial span preproc pre vs post, eval=SPAN_PRINT}
d_all = preproc_pre_v_post(d_pre, d_post, vars_of_interest)
```

```{r spatial span lms pre vs post, eval=SPAN_PRINT}
asis_output("##Pre vs. post\n")
asis_output("###regressions\n")
paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()
d_all %>%
  with(summary(lm(var1_diff ~ grade * gender)))
```

```{r spatial span graphs pre vs post, eval=SPAN_PRINT}
asis_output("###graphs\n")
paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()

d_long = make_long_pvp(d_all)

d_long %>%
  ggplot(aes(x = grade_label, y = count_span.overall, fill = factor(gender))) +
  geom_boxplot() +
  facet_grid(~ pre_or_post) +
  labs(y = vars_of_interest_long[1]) +
  guides(fill = guide_legend(title = "Gender"))
```


```{r setting vars for backward span READ ME}
this_task = "BACKWARDSSPATIALSPAN"
this_task_long = "Backward spatial span"
vars_of_interest = "object_count_span.overall"
vars_of_interest_long = "Overall span (obj count)" # nice version for printing in graphs
# NOT running the outlier check on the object span metric... I think I broke grubbs.test
score_vars = vars_of_interest
score_formula = NA
```

```{r setting vars for stroop READ ME}
this_task = "STROOP"
this_task_long = "Stroop task"
vars_of_interest = c("rt_mean.congruent","rt_mean.incongruent","rt_mean.cost")
vars_of_interest_long = c("Mean RT--congruent trials", "Mean RT--incongruent trials", "Mean cost of incongruence on RT") # nice version for printing in graphs
score_vars = c("rt_mean.congruent", "rt_mean.incongruent")
score_formula = "fraction"
```


```{r stroop load, eval = STROOP_PRINT}
paste0("#", this_task_long) %>% asis_output()
cat("\n") %>% asis_output() # need this for line breaking

d_pre_raw <- proc_pre[[this_task]]
d_post_raw <- proc_post[[this_task]]

d_pre = remove_outlier_subs(d_pre_raw, vars_of_interest) %>%
  brt_append(brt_pre) %>%
  clean_grade_gender()
```

```{r score feedback stroop pre, eval=STROOP_PRINT}
asis_output("##Pre\n")
asis_output("###mean scores for giving feedback in task\n")

d_score = calc_scores(d_pre, score_vars, score_formula)
print(d_score)
```

```{r qc graphs stroop pre, eval=(STROOP_PRINT & QC_HIST_PRINT)}
asis_output("###quality control histograms\n")
paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()

d_pre %>%
  ggplot(aes(x = get(vars_of_interest[1]), fill = factor(grade_label))) +
  geom_histogram(bins=20, position="dodge") +
  labs(x = vars_of_interest_long[1]) +
  guides(fill = guide_legend(title = "Grade"))

asis_output(cat("####", vars_of_interest_long[2], "\n"))
d_pre %>%
  ggplot(aes(x = get(vars_of_interest[2]), fill = factor(grade_label))) +
  geom_histogram(bins=20, position="dodge") +
  labs(x = vars_of_interest_long[2]) +
  guides(fill = guide_legend(title = "Grade"))

asis_output(cat("####", vars_of_interest_long[3], "\n"))
d_pre %>%
  ggplot(aes(x = get(vars_of_interest[3]), fill = factor(grade_label))) +
  geom_histogram(bins=20, position="dodge") +
  labs(x = vars_of_interest_long[3]) +
  guides(fill = guide_legend(title = "Grade"))
```

```{r lms stroop pre, eval=STROOP_PRINT}
asis_output("###regressions\n")
paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()
d_pre %>%
  with(summary(lm(get(vars_of_interest[1]) ~ grade * gender + scale(brt_rt_mean.overall, scale = Z_SCORE_XREGS))))

paste("####", vars_of_interest_long[2], sep = "") %>%
  asis_output()
d_pre %>%
  with(summary(lm(get(vars_of_interest[2]) ~ grade * gender + scale(brt_rt_mean.overall, scale = Z_SCORE_XREGS))))

paste("####", vars_of_interest_long[3], sep = "") %>%
  asis_output()
d_pre %>%
  with(summary(lm(get(vars_of_interest[3]) ~ grade * gender + scale(brt_rt_mean.overall, scale = Z_SCORE_XREGS))))
```

```{r stroop post outliers, eval = STROOP_PRINT}
d_post <- remove_outlier_subs(d_post_raw, vars_of_interest) %>%
  brt_append(brt_post) %>%
  clean_grade_gender()
```

```{r score feedback stroop post, eval=STROOP_PRINT}
asis_output("##Post\n")
asis_output("###mean scores for giving feedback in task\n")

d_score = calc_scores(d_post, score_vars, score_formula)
print(d_score)
```

```{r qc graphs stroop post, eval=(STROOP_PRINT & QC_HIST_PRINT)}
asis_output("###quality control histograms\n")
paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()
d_post %>%
  ggplot(aes(x = get(vars_of_interest[1]), fill = factor(grade_label))) +
  geom_histogram(bins=20, position="dodge") +
  labs(x = vars_of_interest_long[1]) +
  guides(fill = guide_legend(title = "Grade"))

paste("####", vars_of_interest_long[2], sep = "") %>%
  asis_output()
d_post %>%
  ggplot(aes(x = get(vars_of_interest[2]), fill = factor(grade_label))) +
  geom_histogram(bins=20, position="dodge") +
  labs(x = vars_of_interest_long[2]) +
  guides(fill = guide_legend(title = "Grade"))

paste("####", vars_of_interest_long[3], sep = "") %>%
  asis_output()
d_post %>%
  ggplot(aes(x = get(vars_of_interest[3]), fill = factor(grade_label))) +
  geom_histogram(bins=20, position="dodge") +
  labs(x = vars_of_interest_long[3]) +
  guides(fill = guide_legend(title = "Grade"))
```

```{r lms stroop post, eval=STROOP_PRINT}
asis_output("###regressions\n")
paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()
d_post %>%
  with(summary(lm(get(vars_of_interest[1]) ~ grade * gender + scale(brt_rt_mean.overall, scale = Z_SCORE_XREGS))))

paste("####", vars_of_interest_long[2], sep = "") %>%
  asis_output()
d_post %>%
  with(summary(lm(get(vars_of_interest[2]) ~ grade * gender + scale(brt_rt_mean.overall, scale = Z_SCORE_XREGS))))

paste("####", vars_of_interest_long[3], sep = "") %>%
  asis_output()
d_post %>%
  with(summary(lm(get(vars_of_interest[3]) ~ grade * gender + scale(brt_rt_mean.overall, scale = Z_SCORE_XREGS))))
```

```{r stroop preproc pre vs post, eval=STROOP_PRINT}
d_all = preproc_pre_v_post(d_pre, d_post, vars_of_interest)
```

```{r stroop lms pre vs post, eval=STROOP_PRINT}
asis_output("##Pre vs. post\n")
asis_output("###regressions\n")
asis_output(cat("####", vars_of_interest_long[1], "\n"))
d_all %>%
  with(summary(lm(var1_diff ~ grade * gender)))

asis_output(cat("####", vars_of_interest_long[2], "\n"))
d_all %>%
  with(summary(lm(var2_diff ~ grade * gender)))

asis_output(cat("####", vars_of_interest_long[3], "\n"))
d_all %>%
  with(summary(lm(var3_diff ~ grade * gender)))
```

```{r stroop graphs pre vs post, eval=STROOP_PRINT}
asis_output("###graphs\n")

d_long = make_long_pvp(d_all)

paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()

d_long %>%
  ggplot(aes(x = grade_label, y = get(vars_of_interest[1]), fill = factor(gender))) +
  geom_boxplot() +
  facet_grid(~ pre_or_post) +
  labs(y = vars_of_interest_long[1]) +
  guides(fill = guide_legend(title = "Gender"))

paste("####", vars_of_interest_long[2], sep = "") %>%
  asis_output()

d_long %>%
  ggplot(aes(x = grade_label, y = get(vars_of_interest[2]), fill = factor(gender))) +
  geom_boxplot() +
  facet_grid(~ pre_or_post) +
  labs(y = vars_of_interest_long[2]) +
  guides(fill = guide_legend(title = "Gender"))

paste("####", vars_of_interest_long[3], sep = "") %>%
  asis_output()

d_long %>%
  ggplot(aes(x = grade_label, y = get(vars_of_interest[3]), fill = factor(gender))) +
  geom_boxplot() +
  facet_grid(~ pre_or_post) +
  labs(y = vars_of_interest_long[3]) +
  guides(fill = guide_legend(title = "Gender"))
```

```{r setting vars for task switch READ ME}
this_task = "TASKSWITCH"
this_task_long = "Task switch"
vars_of_interest = c("rt_mean.stay","rt_mean.switch")
vars_of_interest_long = c("Mean RT--stay trials", "Mean RT--switch trials") # nice version for printing in graphs
score_vars = vars_of_interest 
score_formula = NA
```


```{r task switch load, eval = SWITCH_PRINT}
paste0("#", this_task_long) %>% asis_output()
cat("\n") %>% asis_output() # need this for line breaking

d_pre_raw <- proc_pre[[this_task]]
d_post_raw <- proc_post[[this_task]]

d_pre = remove_outlier_subs(d_pre_raw, vars_of_interest) %>%
  brt_append(brt_pre) %>%
  clean_grade_gender()
```

```{r score feedback task switch pre, eval=SWITCH_PRINT}
asis_output("##Pre\n")
asis_output("###mean scores for giving feedback in task\n")

d_score = calc_scores(d_pre, score_vars, score_formula)
print(d_score)
```

```{r qc graphs task switch pre, eval=(SWITCH_PRINT & QC_HIST_PRINT)}
asis_output("###quality control histograms\n")
paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()

d_pre %>%
  ggplot(aes(x = get(vars_of_interest[1]), fill = factor(grade_label))) +
  geom_histogram(bins=20, position="dodge") +
  labs(x = vars_of_interest_long[1]) +
  guides(fill = guide_legend(title = "Grade"))

asis_output(cat("####", vars_of_interest_long[2], "\n"))
d_pre %>%
  ggplot(aes(x = get(vars_of_interest[2]), fill = factor(grade_label))) +
  geom_histogram(bins=20, position="dodge") +
  labs(x = vars_of_interest_long[2]) +
  guides(fill = guide_legend(title = "Grade"))
```

```{r lms task switch pre, eval=SWITCH_PRINT}
asis_output("###regressions\n")
paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()
d_pre %>%
  with(summary(lm(get(vars_of_interest[1]) ~ grade * gender + scale(brt_rt_mean.overall, scale = Z_SCORE_XREGS))))

paste("####", vars_of_interest_long[2], sep = "") %>%
  asis_output()
d_pre %>%
  with(summary(lm(get(vars_of_interest[2]) ~ grade * gender + scale(brt_rt_mean.overall, scale = Z_SCORE_XREGS))))
```

```{r task switch post outliers, eval = SWITCH_PRINT}
d_post <- remove_outlier_subs(d_post_raw, vars_of_interest) %>%
  brt_append(brt_post) %>%
  clean_grade_gender()
```

```{r score feedback task switch post, eval=SWITCH_PRINT}
asis_output("##Post\n")
asis_output("###mean scores for giving feedback in task\n")

d_score = calc_scores(d_post, score_vars, score_formula)
print(d_score)
```

```{r qc graphs task switch post, eval=(SWITCH_PRINT & QC_HIST_PRINT)}
asis_output("###quality control histograms\n")
paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()
d_post %>%
  ggplot(aes(x = get(vars_of_interest[1]), fill = factor(grade_label))) +
  geom_histogram(bins=20, position="dodge") +
  labs(x = vars_of_interest_long[1]) +
  guides(fill = guide_legend(title = "Grade"))

paste("####", vars_of_interest_long[2], sep = "") %>%
  asis_output()
d_post %>%
  ggplot(aes(x = get(vars_of_interest[2]), fill = factor(grade_label))) +
  geom_histogram(bins=20, position="dodge") +
  labs(x = vars_of_interest_long[2]) +
  guides(fill = guide_legend(title = "Grade"))
```

```{r lms task switch post, eval=SWITCH_PRINT}
asis_output("###regressions\n")
paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()
d_post %>%
  with(summary(lm(get(vars_of_interest[1]) ~ grade * gender + scale(brt_rt_mean.overall, scale = Z_SCORE_XREGS))))

paste("####", vars_of_interest_long[2], sep = "") %>%
  asis_output()
d_post %>%
  with(summary(lm(get(vars_of_interest[2]) ~ grade * gender + scale(brt_rt_mean.overall, scale = Z_SCORE_XREGS))))
```

```{r task switch preproc pre vs post, eval=SWITCH_PRINT}
d_all = preproc_pre_v_post(d_pre, d_post, vars_of_interest)
```

```{r task switch lms pre vs post, eval=SWITCH_PRINT}
asis_output("##Pre vs. post\n")
asis_output("###regressions\n")
asis_output(cat("####", vars_of_interest_long[1], "\n"))
d_all %>%
  with(summary(lm(var1_diff ~ grade * gender)))

asis_output(cat("####", vars_of_interest_long[2], "\n"))
d_all %>%
  with(summary(lm(var2_diff ~ grade * gender)))
```

```{r task switch graphs pre vs post, eval=SWITCH_PRINT}
asis_output("###graphs\n")

d_long = make_long_pvp(d_all)

paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()

d_long %>%
  ggplot(aes(x = grade_label, y = get(vars_of_interest[1]), fill = factor(gender))) +
  geom_boxplot() +
  facet_grid(~ pre_or_post) +
  labs(y = vars_of_interest_long[1]) +
  guides(fill = guide_legend(title = "Gender"))

paste("####", vars_of_interest_long[2], sep = "") %>%
  asis_output()

d_long %>%
  ggplot(aes(x = grade_label, y = get(vars_of_interest[2]), fill = factor(gender))) +
  geom_boxplot() +
  facet_grid(~ pre_or_post) +
  labs(y = vars_of_interest_long[2]) +
  guides(fill = guide_legend(title = "Gender"))
```

```{r setting vars for tap n trace READ ME}
this_task = "TNT"
this_task_long = "Tap and trace"
vars_of_interest = c("rt_mean.tap_only","rt_mean.tap_trace")
vars_of_interest_long = c("Mean RT--tap only trials", "Mean RT--tap and trace trials") # nice version for printing in graphs
score_vars = vars_of_interest
score_formula = NA
```

```{r tap n trace load, eval = TNT_PRINT}
paste0("#", this_task_long) %>% asis_output()
cat("\n") %>% asis_output() # need this for line breaking

d_pre_raw <- proc_pre[[this_task]]
d_post_raw <- proc_post[[this_task]]

d_pre = remove_outlier_subs(d_pre_raw, vars_of_interest) %>%
  brt_append(brt_pre) %>%
  clean_grade_gender()
```

```{r score feedback tap n trace pre, eval=TNT_PRINT}
asis_output("##Pre\n")
asis_output("###mean scores for giving feedback in task\n")

d_score = calc_scores(d_pre, score_vars, score_formula)
print(d_score)
```

```{r qc graphs tap n trace pre, eval=(TNT_PRINT & QC_HIST_PRINT)}
asis_output("###quality control histograms\n")
paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()

d_pre %>%
  ggplot(aes(x = get(vars_of_interest[1]), fill = factor(grade_label))) +
  geom_histogram(bins=20, position="dodge") +
  labs(x = vars_of_interest_long[1]) +
  guides(fill = guide_legend(title = "Grade"))

asis_output(cat("####", vars_of_interest_long[2], "\n"))
d_pre %>%
  ggplot(aes(x = get(vars_of_interest[2]), fill = factor(grade_label))) +
  geom_histogram(bins=20, position="dodge") +
  labs(x = vars_of_interest_long[2]) +
  guides(fill = guide_legend(title = "Grade"))
```

```{r lms tap n trace pre, eval=TNT_PRINT}
asis_output("###regressions\n")
paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()
d_pre %>%
  with(summary(lm(get(vars_of_interest[1]) ~ grade * gender + scale(brt_rt_mean.overall, scale = Z_SCORE_XREGS))))

paste("####", vars_of_interest_long[2], sep = "") %>%
  asis_output()
d_pre %>%
  with(summary(lm(get(vars_of_interest[2]) ~ grade * gender + scale(brt_rt_mean.overall, scale = Z_SCORE_XREGS))))
```

```{r tap n trace post outliers, eval = TNT_PRINT}
d_post <- remove_outlier_subs(d_post_raw, vars_of_interest) %>%
  brt_append(brt_post) %>%
  clean_grade_gender()
```

```{r score feedback tap n trace post, eval=TNT_PRINT}
asis_output("##Post\n")
asis_output("###mean scores for giving feedback in task\n")

d_score = calc_scores(d_post, score_vars, score_formula)
print(d_score)
```

```{r qc graphs tap n trace post, eval=(TNT_PRINT & QC_HIST_PRINT)}
asis_output("###quality control histograms\n")
paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()
d_post %>%
  ggplot(aes(x = get(vars_of_interest[1]), fill = factor(grade_label))) +
  geom_histogram(bins=20, position="dodge") +
  labs(x = vars_of_interest_long[1]) +
  guides(fill = guide_legend(title = "Grade"))

paste("####", vars_of_interest_long[2], sep = "") %>%
  asis_output()
d_post %>%
  ggplot(aes(x = get(vars_of_interest[2]), fill = factor(grade_label))) +
  geom_histogram(bins=20, position="dodge") +
  labs(x = vars_of_interest_long[2]) +
  guides(fill = guide_legend(title = "Grade"))
```

```{r lms tap n trace post, eval=TNT_PRINT}
asis_output("###regressions\n")
paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()
d_post %>%
  with(summary(lm(get(vars_of_interest[1]) ~ grade * gender + scale(brt_rt_mean.overall, scale = Z_SCORE_XREGS))))

paste("####", vars_of_interest_long[2], sep = "") %>%
  asis_output()
d_post %>%
  with(summary(lm(get(vars_of_interest[2]) ~ grade * gender + scale(brt_rt_mean.overall, scale = Z_SCORE_XREGS))))
```

```{r tap n trace preproc pre vs post, eval=TNT_PRINT}
d_all = preproc_pre_v_post(d_pre, d_post, vars_of_interest)
```

```{r tap n trace lms pre vs post, eval=TNT_PRINT}
asis_output("##Pre vs. post\n")
asis_output("###regressions\n")
asis_output(cat("####", vars_of_interest_long[1], "\n"))
d_all %>%
  with(summary(lm(var1_diff ~ grade * gender)))

asis_output(cat("####", vars_of_interest_long[2], "\n"))
d_all %>%
  with(summary(lm(var2_diff ~ grade * gender)))
```

```{r tap n trace graphs pre vs post, eval=TNT_PRINT}
asis_output("###graphs\n")

d_long = make_long_pvp(d_all)

paste("####", vars_of_interest_long[1], sep = "") %>%
  asis_output()

d_long %>%
  ggplot(aes(x = grade_label, y = tap_only, fill = factor(gender))) +
  geom_boxplot() +
  facet_grid(~ pre_or_post) +
  labs(y = vars_of_interest_long[1]) +
  guides(fill = guide_legend(title = "Gender"))

paste("####", vars_of_interest_long[2], sep = "") %>%
  asis_output()

d_long %>%
  ggplot(aes(x = grade_label, y = tap_trace, fill = factor(gender))) +
  geom_boxplot() +
  facet_grid(~ pre_or_post) +
  labs(y = vars_of_interest_long[2]) +
  guides(fill = guide_legend(title = "Gender"))
```


```{r setting vars for filter READ ME}
this_task = "FILTER"
this_task_long = "Vogel filtering"
vars_of_interest = c("k.2", "k.4")
vars_of_interest_long = c("k = 2 targets * (Hit - FA)", "k = 4 targets * (Hit - FA)") # nice version for printing in graphs
score_vars = vars_of_interest
score_formula = NA
```
